version: 2.1

orbs:
  python: circleci/python@2.0.3
  docker: circleci/docker@2.1.4

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install --no-cache-dir -r requirements.txt

  publish:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKERHUB_LOGIN
          docker-password: DOCKERHUB_PASSWORD
      - docker/build:
          image: nzj002/flask-docker-app
      - docker/push:
          image: nzj002/flask-docker-app

workflows:
  build_and_publish:
    jobs:
      - build
      - publish:
          requires:
            - build
