version: 2.1

orbs:
  python: circleci/python@2.2.1
  docker: circleci/docker@2.5.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/load-cache
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - python/save-cache

  publish:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKERHUB_LOGIN
          docker-password: DOCKERHUB_PASSWORD
      - docker/build:
          image: nzj002/flask-docker-app
      - docker/push:
          image: nzj002/flask-docker-app

workflows:
  build_and_publish:
    jobs:
      - build
      - publish:
          requires:
            - build
